mywebsite/urls.py
from django.contrib import admin
from django.urls import path, include

from . import views
from person_detector import views as viewsPersonDetector

from django.conf.urls.static import static
from django.conf import settings
from django.contrib.auth.views import LogoutView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('login/', views.login_page, name='login'),
    path('logout/', LogoutView.as_view(next_page='login'), name='logout'),
    path('', views.index, name='landing-page'),
    path('person-detector/', include('person_detector.urls')),
    path('memory-tray-detector/', include('memory_tray_detector.urls')),
    path('trash-can-detector/', include('trash_can_detector.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

person_detector/urls.py
from django.urls import path
from django.contrib.auth.views import LogoutView
from . import views

app_name = 'person_detector'
urlpatterns = [
    path('', views.home, name='home'),
    # path('login/', views.login_page, name='login'),
    # path('logout/', LogoutView.as_view(next_page='person_detector:login'), name='logout'),
    path('database/', views.database, name='database'),
    path('database/add/', views.post_database, name='add-database'),
    # path('database/train/', views.train_data, name='train_data'),
    path('open/', views.cam, name='open_cam'),
    path('database/delete/<int:delete_id>', views.delete, name='delete_data'),
    path('database/update/<int:update_id>', views.update, name='update_data'),
    path('reset-all-detected-face/', views.reset_all, name='reset-all-detected-face'),
    path('export/', views.export_detected_dace, name='export-detected-face'),
    path('gallery/', views.gallery, name='gallery'),
]

person_detector/models.py
from django.db import models

import os

# untuk menambahkan data person
class Post(models.Model):
    name = models.CharField(max_length=20)
    fullName = models.CharField(max_length=50)
    date_created = models.DateField(auto_now_add=True)
    picture = models.ImageField(upload_to='person_detector', null=True)

    def __str__(self):
        return self.name
    
    def delete(self, *args, **kwargs):
        self.picture.delete()
        super().delete(*args, **kwargs)  

# untuk menyimpan person yang terdeteksi
class DetectedFace(models.Model):
    name = models.CharField(max_length=100)
    detected_time = models.DateTimeField()
    detected_day = models.DateField(auto_now_add=True)

    def __str__(self):
        return f"{self.name} ({self.detected_time})"

person_detector/forms.py
from django import forms
from .models import Post

class PostForm(forms.ModelForm):
    picture = forms.ImageField(label="Picture", widget=forms.FileInput(attrs={'class': 'form-control'}))
    class Meta:
        model = Post
        fields = [
            'name',
            'fullName',
            'picture'
        ]
    
        widgets = {
            'name': forms.TextInput(
                attrs = {
                    'class': 'form-control',
                    'placeholder': 'Fill with one word and this field can\'t be updated'
                }
            ),
            'fullName': forms.TextInput(
                attrs = {
                    'class': 'form-control',
                    'placeholder': 'Fill with your full name'
                },
            ),
        }

        

person_detector/views.py
from django.shortcuts import render, redirect, HttpResponse
from django.contrib import messages
from .models import Post, DetectedFace
from .forms import PostForm
from django.http import HttpResponse
# from .ml_models.test import train
from .ml_models.main import open_camera
from .filters import DatabaseFilter, DetectedFilter
from django.conf import settings
from datetime import date
from .resource import DetectedFaceResource
from django.contrib.auth import authenticate, login
from django.contrib.auth.decorators import login_required, permission_required, user_passes_test
from django.contrib.auth.models import Group, User

import os


@login_required(login_url='login')
def home(request):
    detected = DetectedFace.objects.all().order_by('-id')
    myFilters = DetectedFilter(request.GET, queryset=detected)

    detected = myFilters.qs
    total_data = len(detected) #untuk menghitung jumlah object

    print(request.user.get_all_permissions())

    context = {
        'title' : 'Person Detector | Home',
        'detected': detected,
        'myFilters': myFilters,
        'total_data': total_data
    }

    return render(request, 'person_detector/home.html', context)

@login_required(login_url='login')
def export_detected_dace(reqeust):
    detected_face = DetectedFaceResource()
    dataset = detected_face.export()
    response = HttpResponse(dataset.csv, content_type='text/csv')
    response['Content-Disposition'] = 'attachment; filename=all_detectted_face_record.csv'
    return response

@login_required(login_url='login')
def cam(request):
    if request.method == 'GET':
        success, error = open_camera()

        if success:
            messages.success(request, 'Camera Has Been Succesfully Opened')
        else:
            messages.error(request, f'Camera Cannot Opened with error: {error}')
    return redirect('person_detector:home')

@login_required(login_url='login')
def database(request):
    post_person = Post.objects.all()
    myFilters = DatabaseFilter(request.GET, queryset=post_person)
    post_person = myFilters.qs
    total_data = len(post_person) #untuk menghitung jumlah object
    context = {
        'title' : 'Person Detector | Database',
        'post': post_person,
        'myFilters': myFilters,
        'total_data': total_data
    }
    return render(request, 'person_detector/database.html', context)

@login_required(login_url='login')
def post_database(request):
    post_person = Post.objects.all() 
    post_form = PostForm(request.POST or None, request.FILES)
    if request.method == "POST":
        if post_form.is_valid():
            name = post_form.cleaned_data['name']
            
            # validasi agar name yang diinput tidak sama dengan name yang sudah ada
            if Post.objects.filter(name=name).exists():
                messages.error(request, f'{name} already exists in the database.')
                return redirect('person_detector:database')

            picture = request.FILES['picture']
            post = post_form.save(commit=False)
            post.picture = picture

            ext = picture.name.split('.')[-1] #mendapatkan ekstensi
            filename = f'{name}.{ext}'
            post.picture.name = filename
            post.save()

            for person in post_person:
                name = person.name           
            messages.success(request, f'{name} successfully added')
            return redirect('person_detector:database')
    
    myFilters = DatabaseFilter(request.GET, queryset=post_person)
    post_person = myFilters.qs  
    context = {
        'title': 'Add Database',
        'action': 'Submit',
        'post_form': post_form,
        'post': post_person,
        'myFilters': myFilters
    }
    return render(request, 'person_detector/add_database.html', context)

# def train_data(request):
#     image_folder = 'static/images/person_detector/'
#     folder = os.path.join(settings.BASE_DIR, image_folder)
    
#     train(folder)

#     if True:
#         messages.success(request, 'Data berhasil ditrain')
#         return redirect('person_detector:database')

@login_required(login_url='login')
def delete(request, delete_id):
    objcet = Post.objects.get(id = delete_id)
    objcet.delete()
    pesan = 'Data deleted successfully'            
    messages.success(request, pesan)
    return redirect('person_detector:database')

@login_required(login_url='login')
def update(request, update_id):
    post_person = Post.objects.all()
    form = Post.objects.get(id = update_id)
    name = form.name

    if request.method == 'POST' :
        # name = request.POST.get('name')
        if len(request.FILES) != 0:
            if len(form.picture) > 0:
                os.remove(form.picture.path)
            picture = request.FILES['picture']
            form.picture = picture

            ext = picture.name.split('.')[-1] #mendapatkan ekstensi
            filename = f'{name}.{ext}'
            form.picture.name = filename

        
        form.fullName = request.POST.get('fullName')


        form.save()

        messages.success(request, 'Data successfully updated')
        return redirect('person_detector:database')
    
    context = {
        'title': 'Update Database',
        'form': form,
        'action': 'Update',
        'post': post_person,
    }

    return render(request, 'person_detector/update_database.html', context)

@login_required(login_url='login')
def reset_all(request):
    obj = DetectedFace.objects.all()
    obj.delete()

    messages.success(request, f'All detected faces have been successfully deleted.')
    return redirect('person_detector:home')


def gallery(request):
    context = {
        'title': 'Person Detector | Gallery'
    }
    return render(request, 'person_detector/gallery.html', context)

person_detector/templates/person_detector/add_database.html
{% extends 'person_detector/database.html' %}

{% block add_database %}
        
        <div class="container shadow rounded mt-3">
            <h5>{{title}}</h5>
            <form method="POST" enctype="multipart/form-data" class="col">
                {% csrf_token %}
                    
                {% for form in post_form %}
                    <div class="col-auto">
                        {{form.label}}
                    </div>                        
                            
                    <div class="col-auto">
                        {{form}}
                    </div>
                {% endfor %}
                {% if update_data.picture %}
                    <img src="{{update_data.picture.url}}" alt="" width="90px">
                {% endif %} 

                <div>
                    <button type="submit" class="btn btn-success my-4">{{action}}</button>
                    <a href="{% url 'person_detector:database' %}" class="btn btn-danger">Back</a>
                </div>

            </form>
        </div>
{% endblock add_database %}


    

person_detector/templates/person_detector/database.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
    {{title}}
{% endblock title %}


{% block list %}
  <li class="nav-item ps-4">
    <a class="nav-link" href="{% url 'person_detector:home' %}">Home</a>
  </li>
  <li class="nav-item ps-4">
    <a class="nav-link active" aria-current="page" href="{% url 'person_detector:database' %}">Database</a>
  </li>
  <li class="nav-item ps-4">
    <a class="nav-link" href="" data-bs-toggle="modal" data-bs-target="#logout-user">Logout</a>
  </li>
{% endblock list %}
  


{% block content %}    
    {% block add_database %}
        
    {% endblock add_database %}
    
    <div class="container mt-3" style="font-family: 'Poppins', sans-serif; font-weight: 400;">

      <!-- modal untuk logout -->
      <div class="modal fade" id="logout-user" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered">
          <div class="modal-content">
            <div class="modal-header bg-main text-light">
              <h1 class="modal-title fs-5" id="exampleModalLabel">LOGOUT</h1>
              <button type="button" class="btn-close bg-light" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
              Are you sure to <strong>Logout</strong>?
            </div>
            <div class="modal-footer">
              <a href="{% url 'logout' %}" class="btn btn-danger">Logout</a>
              <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
            </div>
          </div>
        </div>
      </div>

      <div class="d-flex justify-content-between">
        <h5>Person Detector | Database </h5>
        <h5>Active | {{user.first_name}}</h5>
      </div>


      <div class="d-flex justify-content-between">
        <a href="{% url 'person_detector:add-database' %}" class="btn btn-primary my-1">Add Person</a>

      <p class="mb-0 mt-0 d-flex align-items-end">Current Data : <strong>{{total_data}}</strong></p>
      </div>
      
      
      <!-- messages -->
      <div>
        {% if messages %}
         {% for msg in messages %}
            <div class="alert {% if msg.tags == 'success' %}alert-success{% elif msg.tags == 'error' %}alert-danger{% endif %} alert-dismissible fade show d-sm-inline-flex" role="alert">
                {{ msg }}
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
          {% endfor %}
        {% endif %}
      </div>
      <!-- Filter -->
      <div class="row mt-2 mb-2">
        <div class="col">
          <div class="card card-body">
            <div class="d-flex justify-content-between">
              <div>
                <form method="GET" class="row g-2 align-items-center">
                  <div class="col-auto align-middle">
                    {{myFilters.form.name.label}}
                  </div>
                  <div class="col-auto">
                    {{myFilters.form.name}}
                  </div>                    
                  <div class="col-auto">
                    <button type="submit" class="btn btn-primary">Search</button>
                  </div>
                  <div class="col-auto">
                    <a href="{% url 'person_detector:database' %}" class="btn btn-danger">Back to See All</a>
                  </div>
    
                  
                </form>
              </div>

            </div>
          </div>
        </div>
      </div>
      <!-- Akhir -->

      <!-- Tabel -->
      <div class="scroll">
        <table class="table table-striped table-hover table-bordered table-sm rounded rounded-lg">
          <thead>
            <tr>
              <th scope="col" class="text-center">Number</th>
              <th scope="col" class="text-center">Picture</th>
              <th scope="col" class="text-center">Name</th>
              <th scope="col" class="text-center">Full Name</th>
              <th scope="col" class="text-center">Date Created</th>
              <th scope="col" class="text-center">Delete</th>
              <th scope="col" class="text-center">Update</th>
            </tr>
          </thead>
          <tbody>
            {% for data in post %}
              <tr>
                <td scope="row" class="text-center align-middle">{{forloop.counter}}</td>
                <td class="text-center align-middle">                 
                  {% if data.picture %}
                   <img src="{{data.picture.url}}" alt="" width="90px">
                  {% endif %}                  
                </td>
                <td class="text-center align-middle">{{data.name}}</td>
                <td class="text-center align-middle">{{data.fullName}}</td>
                <td class="text-center align-middle">{{data.date_created}}</td>
                <td class="text-center align-middle">
                  <button type="button" class="btn btn-danger" data-bs-toggle="modal" data-bs-target="#delete-{{data.id}}">
                    Delete
                  </button>
                </td>
                <!-- Modal -->
                <div class="modal fade" id="delete-{{data.id}}" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                  <div class="modal-dialog modal-dialog-centered">
                    <div class="modal-content">
                      <div class="modal-header bg-main text-light">
                        <h1 class="modal-title fs-5" id="exampleModalLabel">DELETE</h1>
                        <button type="button" class="btn-close bg-light" data-bs-dismiss="modal" aria-label="Close"></button>
                      </div>
                      <div class="modal-body">
                        Are you sure to delete <strong>"{{data.name}}"</strong> data?
                      </div>
                      <div class="modal-footer">
                        <a href="{% url 'person_detector:delete_data' data.id %}" class="btn btn-danger">Delete</a>
                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
                      </div>
                    </div>
                  </div>
                </div>
                <td class="text-center align-middle">
                  <a href="{% url 'person_detector:update_data' data.id %}" class="btn btn-warning">Update</a>
                </td>
              </tr>
            {% endfor %}             
          </tbody>
        </table>
      </div>
      <!-- Akhir Tabel -->

    </div>    
          
{% endblock content %}
    
    

person_detector/templates/person_detector/gallery.html
{% extends 'base.html' %}

{% block list %}
<li class="nav-item ps-4">
    <a class="nav-link" href="{% url 'person_detector:home' %}">Home</a>
  </li>
  <li class="nav-item ps-4">
    <a class="nav-link" href="{% url 'person_detector:database' %}">Database</a>
  </li>
  <li class="nav-item ps-4">
    <a class="nav-link" href="{% url 'person_detector:logout' %}">Logout</a>
  </li>    
{% endblock list %}
    

{% block title %}
    {{title}}
{% endblock title %}
    

person_detector/templates/person_detector/home.html
{% extends 'base.html' %}


{% block title %}
    {{title}}
{% endblock title %}


{% block list %}
<li class="nav-item ps-4">
    <a class="nav-link active" aria-current="page" href="{% url 'person_detector:home' %}">Home</a>
  </li>
  <li class="nav-item ps-4">
    <a class="nav-link" href="{% url 'person_detector:database' %}">Database</a>
  </li>
  <li class="nav-item ps-4">
    <a class="nav-link" href="" data-bs-toggle="modal" data-bs-target="#logout-user">Logout</a>
  </li>    
{% endblock list %}
    

{% block content %}

<div class="container mt-3" style="font-family: 'Poppins', sans-serif; font-weight: 400;">

  <!-- modal untuk logout -->
  <div class="modal fade" id="logout-user" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
      <div class="modal-content">
        <div class="modal-header bg-main text-light">
          <h1 class="modal-title fs-5" id="exampleModalLabel">LOGOUT</h1>
          <button type="button" class="btn-close bg-light" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
          Are you sure to <strong>Logout</strong>?
        </div>
        <div class="modal-footer">
          <a href="{% url 'logout' %}" class="btn btn-danger">Logout</a>
          <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
        </div>
      </div>
    </div>
  </div>

  <div class="d-flex justify-content-between">
    <h5>Person Detector | Home </h5>
    <h5>Active | {{user.first_name}}</h5>
  </div>

  <div class="d-flex justify-content-between">
    <div class="align-middle">
      <a href="{% url 'person_detector:open_cam' %}" class="btn btn-success my-1">START DETECTION</a>
    </div>   
    <p class="mb-0 mt-0 d-flex align-items-end">Current Data : <strong>{{total_data}}</strong></p>
  </div>

  <!-- messages -->
  {% if messages %}
        {% for msg in messages %}
            <div class="alert {% if msg.tags == 'success' %}alert-success{% elif msg.tags == 'error' %}alert-danger{% endif %} alert-dismissible fade show d-sm-inline-flex" role="alert">
                {{ msg }}
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
        {% endfor %}
      {% endif %}
  
      <!-- <div class="d-flex justify-content-between mt-2">
        <h5 class="me-2">Detected Name Record</h5>
      </div> -->

  <!-- <p class="mb-0 mt-0">Current Data : <strong>{{total_data}}</strong></p> -->

  <!-- Filter -->
  <div class="row mt-2 mb-2">
    <div class="col">
      <div class="card card-body">
        <div class="d-flex justify-content-between">
          <div>
            <form method="GET" class="row g-2 align-items-center">
              <div class="col-auto align-middle">
                {{myFilters.form.name.label}}
              </div>
              <div class="col-auto">
                {{myFilters.form.name}}
              </div>
              <div class="col-auto align-middle">
                {{myFilters.form.detected_time.label}}
              </div>
              <div class="col-auto">
                {{ myFilters.form.detected_time }}
              </div>
              <div class="col-auto align-middle">
                {{myFilters.form.start_date.label}}
              </div>
              <div class="col-auto">
                <input type="text" id="start_date" name="start_date" class="form-control datepicker" placeholder="Choose Date">
              </div>
              <div class="col-auto align-middle">
                <label for="end_date">{{myFilters.form.end_date.label}}</label>
              </div>
              <div class="col-auto">
                <input type="text" id="end_date" name="end_date" class="form-control datepicker" placeholder="Choose Date">
              </div>
              
              <!-- <div class="d-sm-inline-flex"> -->
                <div class="col-auto pe-2">
                  <button type="submit" class="btn btn-primary">Search</button>
                </div>
                <div class="col-auto">
                  <a href="{% url 'person_detector:home' %}" class="btn btn-danger">Back to All</a>
                </div>
              <!-- </div> -->
            </form>
          </div>
          <!-- <div>
            <p>Current Data : <strong>{{total_data}}</strong></p>
          </div> -->
        </div>
      </div>
    </div>
  </div>
  <!-- Akhir Filter-->

  <div class="d-flex justify-content-between mb-1">
    <h5 class="me-2">Detected Name Record</h5>
    <div>
      <a href="{% url 'person_detector:export-detected-face' %}" class="btn btn-sm btn-success">Download All Record</a>
      <button type="button" href="" class="btn btn-sm btn-danger" data-bs-toggle="modal" data-bs-target="#reset-detected-face-record">Reset All Record</button>
    </div>
  </div>
  <!-- Modal untuk reset detected face -->
  <div class="modal fade" id="reset-detected-face-record" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
      <div class="modal-content">
        <div class="modal-header bg-main text-light">
          <h1 class="modal-title fs-5" id="exampleModalLabel">Reset ALL</h1>
          <button type="button" class="btn-close bg-light" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
          Are you sure to <strong>RESET ALL</strong> detected face records?
        </div>
        <div class="modal-footer">
          <a href="{% url 'person_detector:reset-all-detected-face' %}" class="btn btn-danger">RESET ALL</a>
          <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
        </div>
      </div>
    </div>
  </div>

  
  <!-- Tabel -->
  <div class="scroll">
    <table class="table table-striped table-hover table-bordered table-sm rounded rounded-lg">
      <thead>
        <tr>
          <th scope="col" class="text-center">No.</th>
          <th scope="col" class="text-center">Name Detected</th>
          <th scope="col" class="text-center">Time</th>
          <!-- <th scope="col" class="text-center">Day</th> -->
        </tr>
      </thead>
      <tbody>
        {% for data in detected %}
          <tr>
            <td scope="row" class="text-center align-middle">{{forloop.counter}}</td>
            <td class="text-center align-middle">{{data.name}}</td>
            <td class="text-center align-middle">{{data.detected_time}}</td>
            <!-- <td class="text-center align-middle">{{data.detected_day}}</td> -->
          </tr>
        {% endfor %}             
      </tbody>
    </table>
  </div>
  <!-- Akhir Tabel -->
</div>

<!-- script untuk membuka calender -->
<script>
  flatpickr(".datepicker", {
    dateFormat: "m/d/y",
  });
</script>


{% endblock content %}
    

person_detector/templates/person_detector/login.html
{% extends 'base.html' %}


{% block title %}
    {{title}}    
{% endblock title %}

    

{% block content %}
 <div class="container">

 
    <!-- messages -->
 {% if messages %}
 {% for msg in messages %}
     <div class="alert {% if msg.tags == 'success' %}alert-success{% elif msg.tags == 'error' %}alert-danger{% endif %} alert-dismissible fade show d-sm-inline-flex mt-2" role="alert">
         {{ msg }}
         <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
     </div>
 {% endfor %}
{% endif %}


<!-- Login Card -->
    <div class="row d-flex justify-content-center mt-5">
        <div class="col-md-4">
            <div class="card shadow">
                <div class="card-header bg-main text-light align-middle">
                    <h6 class="text-center">LOGIN PAGE | PERSON DETECTOR</h6>
                </div>
                <div class="card-body">
                    <form method="POST">
                        {% csrf_token %}
    
                        <div class="col-auto">
                            <label for="username" class="form-label">Username:</label>
                            <input type="text" class="form-control" id="username" name="username">
                          </div>
                          <div class="mb-3">
                            <label for="password" class="form-label">Password</label>
                            <input type="password" class="form-control" id="password" name="password">
                          </div>
    
                          <button type="submit" class="btn btn-primary">Login</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
 </div>    

{% endblock content %}
    

person_detector/templates/person_detector/update_database.html
{% extends 'person_detector/database.html' %}

{% block add_database %}
        
        <div class="container shadow rounded mt-3">
            <h5>{{title}}</h5>
            <form method="POST" enctype="multipart/form-data" class="col">
                {% csrf_token %}

                <div class="col-auto">
                    <label for="" class="form-label">Name</label>
                    <input type="text" Required name="name" value="{{form.name}}" class="form-control" disabled>
                </div>
                <div class="col-auto">
                    <label for="" class="form-label">Full Name</label>
                    <input type="text" Required name="fullName" value="{{form.fullName}}" class="form-control">
                </div>
                <div class="col-auto">
                    
                    <label for="" class="form-label">Picture</label>
                    <input type="file" name="picture" class="form-control">
                    {% if form.picture %}
                       <div class="">
                        <p>Current Picture:</p>
                        <img src="{{form.picture.url}}" alt="" width="110px"> 
                       </div>                 
                    {% endif %}
                        
                    
                    
                </div>
                    
                <!-- {% for form in post_form %}
                    <div class="col-auto">
                        {{form.label}}
                    </div>                        
                            
                    <div class="col-auto">
                        {{form}}
                    </div>
                {% endfor %}
                {% if update_data.picture %}
                    <img src="{{update_data.picture.url}}" alt="" width="90px">
                {% endif %}  -->

                <div>
                    <button type="submit" class="btn btn-success my-4">{{action}}</button>
                    <a href="{% url 'person_detector:database' %}" class="btn btn-danger">Back</a>
                </div>

            </form>
        </div>
{% endblock add_database %}


    